<?php
/*
Plugin Name: WP Anber Pricing Plan 
Plugin URI: https://github.com/frahim/
Description: WP Anber Pricing Plan 
Version: 1.0.0
Author: Md Yeasir Arafat
Author URI: https://github.com/frahim
Text Domain: wpfs
Generated By: http://ensuredomains.com
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}
define('WPAPP_CORE_INC', dirname(__FILE__) . '/assets/inc/');

// Load the Carbonfield
if (!file_exists(WPAPP_CORE_INC . '/vendor/autoload.php')) {
    require_once WPAPP_CORE_INC . '/vendor/autoload.php';
}



// Load the Carbonfield
if (file_exists(WPAPP_CORE_INC . '/wapp-core-functions.php')) {
    require_once WPAPP_CORE_INC . '/wapp-core-functions.php';
}

add_action( 'enqueue_block_assets', function() {
    wp_enqueue_style( 'carbon-fields-block-style', plugin_dir_url( __FILE__ ) . '/assets/css/wpapp-block-style.css' );
} );


