<?php
/*
Plugin Name: WP Anber Pricing Plan 
Plugin URI: https://github.com/frahim/
Description: WP Anber Pricing Plan 
Version: 1.0.1
Author: Md Yeasir Arafat
Author URI: https://github.com/frahim
Text Domain: wpfs
Generated By: http://ensuredomains.com
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}
define('WPAPP_CORE_INC', dirname(__FILE__) . '/assets/inc/');

// Load the Carbonfield
if (!file_exists(WPAPP_CORE_INC . '/vendor/autoload.php')) {
    require_once WPAPP_CORE_INC . '/vendor/autoload.php';
}



// Load the Carbonfield
if (file_exists(WPAPP_CORE_INC . '/wapp-core-functions.php')) {
    require_once WPAPP_CORE_INC . '/wapp-core-functions.php';
}

add_action( 'enqueue_block_assets', function() {
    wp_enqueue_style( 'carbon-fields-block-style', plugin_dir_url( __FILE__ ) . '/assets/css/wpapp-block-style.css' );
} );


// Update Chacker
if (file_exists(WPAPP_CORE_INC . '/plugin-update-checker/plugin-update-checker.php')) {
    require_once WPAPP_CORE_INC . '/plugin-update-checker/plugin-update-checker.php';
}

// Start the update checker
use Puc_v4_Factory;

$updateChecker = Puc_v4_Factory::buildUpdateChecker(
    'https://github.com/Frahim/WP-Anber-Pricing-Plan', // GitHub repo URL
    __FILE__,                                             // Full path to the main plugin file
    'WP-Anber-Pricing-Plan'                                    // Plugin slug (used as identifier)
);

// Optional: Set the branch to use for updates (e.g., 'main' or 'master')
$updateChecker->setBranch('main');